database: h2
app:
  issuer-uri: ${HOST_ISSUER_URI:}
server:
  servlet:
    context-path: /api/account
  port: 8083

spring:
  profile: dev
  flyway:
    user: sa
    password: password
    url: jdbc:h2:mem:demo
    locations: classpath:db/migration/${database}
  datasource:
    url: jdbc:h2:mem:demo
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  h2:
    console:
      enabled: true


logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        SQL: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info