database: h2

server:
  servlet:
    context-path: /api/uaa
  port: 9000

spring:
  profile: dev
  security:
    oauth2:
      resource-server:
        issuer-uri: http://localhost:9000/api/uaa #in this case, is ok to have the issuer-uri hardcoded since the issuer will always be the local machine
  flyway:
    user: sa
    password: password
    url: jdbc:h2:mem:demo
    locations: classpath:db/migration/${database}
  datasource:
    url: jdbc:h2:mem:demo
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  h2:
    console:
      enabled: true
  thymeleaf:
    cache: false
  devtools:
    restart:
      exclude: /static/**,/templates/**
    livereload:
      port: 35730
#logging & management
logging:
  level:
    org:
      springframework:
        security: TRACE
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info