server:
  port:
    8061
app:
  issuer-uri: ${HOST_ISSUER_URI:}
spring:
  profile: dev
  cloud:
    gateway:
      metrics:
        enabled: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/uaa/**
          filters:
            - PrefixPath=/api
        - id: account
          uri: lb://account
          predicates:
            - Path=/account/**
          filters:
            - PrefixPath=/api
            - DmFilterFactory=DMSERVICES WORKING IN DEV FOR ACCOUNTS, true, true
        - id: stats
          uri: lb://stats
          predicates:
            - Path=/stats/**
          filters:
            - PrefixPath=/api
            - DmFilterFactory=DMSERVICES WORKING IN DEV FOR STATS, false, true
        - id: noti
          uri: lb://noti
          predicates:
            - Path=/noti/**
          filters:
            - PrefixPath=/api
            - DmFilterFactory=DMSERVICES WORKING IN DEV FOR NOTI, false, true
#resilience4j
resilience4j:
  retry:
    instance:
      accountClient:
        maxRetryAttemps: 3
        waitDuration: 2s
#thymeleaf and dev tools
  thymeleaf:
    cache: false
  devtools:
    restart:
      exclude: /static/**,/templates/**
#logging
logging:
  level:
    reactor:
      netty:
        http:
          client: TRACE
    org:
      springframework:
        cloud:
          gateway: TRACE
        security: TRACE
        web: TRACE
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info