server:
  port: 8085
spring:
  profile: prod
  datasource:
    url: jdbc:postgresql://dmservices-database:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
#logging & management
logging:
  level:
    org:
      springframework:
        security: TRACE
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info
